### ISSUE TITLE
SMILE Support for MPE

### ISSUE THREAD

**Issue by BIKA-C** [Mathpix/vscode-mathpix-markdown#10]
I really like SMILE of the extension.
Would it be possible to support  [Markdown Preview Enhanced](https://github.com/shd101wyy/markdown-preview-enhanced)? 
So I can export md to PDF.

**Comment by montanaflynn** [comment]
Hello, I think we would need to add Mathpix Markdown support to [Markdown Preview Enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) rather than support it the other way around. You could try making an issue on their repo.
