### ISSUE TITLE
QUESTION: Export result

### ISSUE THREAD

**Issue by JBlond** [Mathpix/vscode-mathpix-markdown#12]
All of this looks awesome. How do I export the result from the preview as it looks with the plugin?

**Comment by Acumane** [comment]
Shame... doesn't seem to be compatible with [markdown-pdf](https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf).

**Comment by Acumane** [comment]
The exporter in [Markdown Extended](https://marketplace.visualstudio.com/items?itemName=jebbs.markdown-extended#Exporter) considers contributions by other plugins. Don't think it takes style sheets, unfortunately.

**Comment by ykolodnitskiy** [comment]
@Acumane @JBlond you can export your code as PDF on snip.mathpix.com if you create a note and paste your code there. 

https://mathpix.com/docs/snip/editor-overview#create-and-edit-documents
