### ISSUE TITLE
cause mermaid cannot be rendered

### ISSUE THREAD

**Issue by heartacker** [Mathpix/vscode-mathpix-markdown#14]
https://github.com/mjbvz/vscode-markdown-mermaid/issues/120
install this mathpix, mermaid cannot be rendered

**Comment by adalbertpl** [comment]
Could you fix it? 
I am using mentioned extension which renders mermaid diagrams and when installing mathpix extension mermaid diagrams stop rendering.

**Comment by OlgaRedozubova** [comment]
Fixed in v0.2.1

<img width="1317" alt="Screenshot 2024-11-18 at 20 08 07" src="https://github.com/user-attachments/assets/23cc7c4c-f47b-490c-969c-bf456ffc30eb">
