### ISSUE TITLE
Theorem environment support

### ISSUE THREAD

**Issue by dualer** [Mathpix/vscode-mathpix-markdown#15]
Can you add some native supports for theorem enviroment? E.g., 
```
\begin{theorem}[Name]
\end{theorem}

\begin{solution}
\end{solution}
```

**Comment by ykolodnitskiy** [comment]
@dualer thank you for your suggestion. We will add it soon.

**Comment by dualer** [comment]
This has been added in '[mathpix-markdown-it](https://github.com/Mathpix/mathpix-markdown-it)` , see https://github.com/Mathpix/mathpix-markdown-it/blob/master/doc/theorems.md

**Comment by ykolodnitskiy** [comment]
Thank you for mentioning that @dualer

**Comment by dualer** [comment]
When will it be added into this extension?

**Comment by ykolodnitskiy** [comment]
@dualer it will be added in the next 24 hours (probably less than in 3 hours).

**Comment by OlgaRedozubova** [comment]
> When will it be added into this extension?

This has just been updated
<img width="1068" alt="Screen Shot 2022-12-27 at 20 08 46" src="https://user-images.githubusercontent.com/32493105/209705716-4b302ae0-9083-4835-8136-a2156f8fedbf.png">

https://marketplace.visualstudio.com/items?itemName=mathpix.vscode-mathpix-markdown

**Comment by dualer** [comment]
In the latest version, i.e. v0.1.5, this function no longer works.

**Comment by OlgaRedozubova** [comment]
@dualer I've just tested it - everything is working correctly:

<img width="1170" alt="Screen Shot 2023-02-21 at 06 36 53" src="https://user-images.githubusercontent.com/32493105/220249243-5f28f71b-992f-4f1d-b6ea-87c66aa343cb.png">

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32493105/220249298-5269dbd3-52df-4d18-92b5-415f72ea8ae0.gif)

Did you reload window after install extension?

<img width="662" alt="Screen Shot 2023-02-21 at 06 42 19" src="https://user-images.githubusercontent.com/32493105/220249621-17256efa-96aa-4c4e-81ca-9ebcfcb0a4bd.png">

**Comment by dualer** [comment]
@OlgaRedozubova  I have done what you say, but it still doesn't work.

**Comment by OlgaRedozubova** [comment]
@dualer I tested it on different devices and it works for me.
What version of vsCode are you using?
Are there any additional extensions installed for you?
Could you share md content with me that doesn't work for you?
