### ISSUE TITLE
Hits do not seem to work

### ISSUE THREAD

**Issue by slabko** [Mathpix/vscode-mathpix-markdown#18]
Hits work perfectly in the online version of the editor at https://snip.mathpix.com/
![image](https://user-images.githubusercontent.com/5012202/207833273-d46a2d85-e96f-49e8-beec-e8f0fab71027.png)

but in VSCode they are not shown as hints
![image](https://user-images.githubusercontent.com/5012202/207833349-34af7090-e00b-4d0d-bf95-d7f8e61241d3.png)

**Comment by OlgaRedozubova** [comment]
@slabko It'was fixed in new version https://marketplace.visualstudio.com/items?itemName=mathpix.vscode-mathpix-markdown

<img width="1110" alt="Screen Shot 2022-12-27 at 20 10 48" src="https://user-images.githubusercontent.com/32493105/209705933-68602e70-2389-4263-ac04-544cc78210e7.png">

**Comment by slabko** [comment]
Awesome! It works perfectly!

Thank you @OlgaRedozubova very much!
