### ISSUE TITLE
I can implement VSCODE_MATHPIX_MARKDOWN in ReactJS  ?

### ISSUE THREAD

**Issue by SangVoM** [Mathpix/vscode-mathpix-markdown#29]
I need it on ReactJS, can I use it there? Please guide me to implement it. Thanks
And I found lib https://github.com/Mathpix/mathpix-markdown-it, It can render, So how to get editor for it, which editor should I use that has mathType input?

**Comment by OlgaRedozubova** [comment]
@SangVoM  `vscode-mathpix-markdown` is a vsCode plugin that uses [mathpix-markdown-it](https://github.com/Mathpix/mathpix-markdown-it)

You can use [mathpix-markdown-it](https://github.com/Mathpix/mathpix-markdown-it) for ReactJS
Information can be found [here](https://github.com/Mathpix/mathpix-markdown-it/blob/master/README.md#react-usage).

> So how to get editor for it, which editor should I use that has mathType input?

You can use any text editor. It can be just textarea. Also, you can use [codemirror](https://codemirror.net/) for it.

Example using `textarea`: https://github.com/Mathpix/mathpix-markdown-it/blob/master/examples/react-app/use-parseMarkdownByHTML-method/README.md

**Comment by SangVoM** [comment]
> @SangVoM `vscode-mathpix-markdown` is a vsCode plugin that uses [mathpix-markdown-it](https://github.com/Mathpix/mathpix-markdown-it)
> 
> You can use [mathpix-markdown-it](https://github.com/Mathpix/mathpix-markdown-it) for ReactJS Information can be found [here](https://github.com/Mathpix/mathpix-markdown-it/blob/master/README.md#react-usage).
> 
> > So how to get editor for it, which editor should I use that has mathType input?
> 
> You can use any text editor. It can be just textarea. Also, you can use [codemirror](https://codemirror.net/) for it.
> 
> Example using `textarea`: https://github.com/Mathpix/mathpix-markdown-it/blob/master/examples/react-app/use-parseMarkdownByHTML-method/README.md

Okay, I will try it. Thanks a lot

**Comment by SangVoM** [comment]
I tried one case with [mathpix-markdown-it](https://htmlpreview.github.io/?https://github.com/Mathpix/mathpix-markdown-it/blob/master/examples/html/input-mmd-to-html.html) demo but it couldn't render tabular's newline, but in vscode it was able to render, can you support me?

**Example tabular has $\newline$:** 
```
 \begin{tabular}{|l|l|}
\hline
ACTIVITIES OF TEACHER AND STUDENT & MAIN CONTENT \\
\hline
Step 1. Assigning tasks 
 - Teacher: Organizes students for testing 
 $\newline$ - Student: Understands the teacher's requirements. $\newline$ Step 2. Performing tasks $\newline$ - Student: Takes the test seriously & * Test content: $\newline$ Question 1: State the basic content of $\newline$ the current civil air defense work?. $\newline$ Question 2: Explain the tasks of national $\newline$ security protection?. $\newline$ Question 3: What are the students' responsibilities $\newline$ in the task of national security protection?. \\
\hline
\end{tabular}
```

**VSCode:** 
<img width="549" alt="Screenshot 2024-11-14 at 10 12 24" src="https://github.com/user-attachments/assets/83b0d45d-e1e4-4571-b878-2cf16c004de9">

**DEMO:**
![Screenshot 2024-11-14 at 10 12 50](https://github.com/user-attachments/assets/2f94c401-dd9f-4b05-a20c-4ecdfa67c442)

- Format not support:
`\textbf{\textit{\underline{formatting}}}`

**VScode:** 
<img width="135" alt="Screenshot 2024-11-14 at 10 14 14" src="https://github.com/user-attachments/assets/b60e1ab4-7580-4c44-b013-27e385eab376">

**DEMO:**
![Screenshot 2024-11-14 at 10 14 50](https://github.com/user-attachments/assets/17f2ba1f-0f56-4fca-89ae-b4cac9992bda)

**Comment by OlgaRedozubova** [comment]
> @OlgaRedozubova
> I tried one case with [mathpix-markdown-it](https://htmlpreview.github.io/?https://github.com/Mathpix/mathpix-markdown-it/blob/master/examples/html/input-mmd-to-html.html) demo but it couldn't render tabular's newline, but in vscode it was able to render, can you support me?

Demo uses an outdated version of `mathpix-markdown-it`. I'll fix it.

Just change this `script.src = "https://cdn.jsdelivr.net/npm/mathpix-markdown-it@1.0.40/es5/bundle.js";`
to `script.src = "https://cdn.jsdelivr.net/npm/mathpix-markdown-it@2.0.6/es5/bundle.js"`

<img width="1408" alt="Screenshot 2024-11-14 at 10 06 35" src="https://github.com/user-attachments/assets/0593c016-540a-4c52-8095-24cddb78b210">

**Comment by SangVoM** [comment]
> > @OlgaRedozubova
> > I tried one case with [mathpix-markdown-it](https://htmlpreview.github.io/?https://github.com/Mathpix/mathpix-markdown-it/blob/master/examples/html/input-mmd-to-html.html) demo but it couldn't render tabular's newline, but in vscode it was able to render, can you support me?
> 
> Demo uses an outdated version of `mathpix-markdown-it`. I'll fix it.
> 
> Just change this `script.src = "https://cdn.jsdelivr.net/npm/mathpix-markdown-it@1.0.40/es5/bundle.js";` to `script.src = "https://cdn.jsdelivr.net/npm/mathpix-markdown-it@2.0.6/es5/bundle.js"`
> 
> <img alt="Screenshot 2024-11-14 at 10 06 35" width="1408" src="https://private-user-images.githubusercontent.com/32493105/386100203-0593c016-540a-4c52-8095-24cddb78b210.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzIyNDAsIm5iZiI6MTczMTU3MTk0MCwicGF0aCI6Ii8zMjQ5MzEwNS8zODYxMDAyMDMtMDU5M2MwMTYtNTQwYS00YzUyLTgwOTUtMjRjZGRiNzhiMjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA4MTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYmYxMjljYjhhZTIyOWUwM2FhYzQyZTY4NmU5NjBmODQyMTU0MzRiZmU2MDA4NWRjNWNhODYzNzNhMzI4N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EmhC4cOlRyUfo1FKErgWLjG4WbDWahi5VYK5zU_nu48">

Thanks a lot, Can you suggest an editor that can input MathType and render HTML (i use Mathpix-markdown-it) to view and output Latex?

**Comment by OlgaRedozubova** [comment]
> Thanks a lot, Can you suggest an editor that can input MathType and render HTML (i use Mathpix-markdown-it) to view and output Latex?

You can use [Snip Web](https://snip.mathpix.com)
[Snip web app](https://snip.mathpix.com/) is a simple online editor powered by [Mathpix Markdown](https://mathpix.com/docs/mathpix-markdown).

<img width="1891" alt="Screenshot 2024-11-14 at 10 23 29" src="https://github.com/user-attachments/assets/c4b664f8-0d8a-42ab-8d75-eed95cc61f62">

Documentation https://mathpix.com/docs/snip/editor-overview#create-and-edit-documents

**Comment by SangVoM** [comment]
> > Thanks a lot, Can you suggest an editor that can input MathType and render HTML (i use Mathpix-markdown-it) to view and output Latex?
> 
> You can use [Snip Web](https://snip.mathpix.com) [Snip web app](https://snip.mathpix.com/) is a simple online editor powered by [Mathpix Markdown](https://mathpix.com/docs/mathpix-markdown).
> 
> <img alt="Screenshot 2024-11-14 at 10 23 29" width="1891" src="https://private-user-images.githubusercontent.com/32493105/386104687-c4b664f8-0d8a-42ab-8d75-eed95cc61f62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzMxODksIm5iZiI6MTczMTU3Mjg4OSwicGF0aCI6Ii8zMjQ5MzEwNS8zODYxMDQ2ODctYzRiNjY0ZjgtMGQ4YS00MmFiLThkNzUtZWVkOTVjYzYxZjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA4MjgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYzhmMTkxOTNjZWVlZTZhNWM5NTNjYjE4ZWQzZDIxYjUwMDI0MjFlMGZhODZkNTc4NWI5ZjMwYmNkODQ2ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pX7lTkSuCB1F5zmEw7UTdEBceiXiEc2BdoWDk_St3sk">
> Documentation https://mathpix.com/docs/snip/editor-overview#create-and-edit-documents

I need to implement this into my project, how can do it

**Comment by OlgaRedozubova** [comment]
> I need to implement this into my project, how can do it

For the editing side, you can use any text editor, for example, [Codemirror](https://codemirror.net/)
Then you need to render the entered text content into HTML using [mathpix-markdow-it](https://github.com/Mathpix/mathpix-markdown-it/blob/master/README.md#example-of-markdowntohtml-method-usage)
And paste the resulting HTML into the preview side

**Comment by SangVoM** [comment]
> > @OlgaRedozubova
> > I tried one case with [mathpix-markdown-it](https://htmlpreview.github.io/?https://github.com/Mathpix/mathpix-markdown-it/blob/master/examples/html/input-mmd-to-html.html) demo but it couldn't render tabular's newline, but in vscode it was able to render, can you support me?
> 
> Demo uses an outdated version of `mathpix-markdown-it`. I'll fix it.
> 
> Just change this `script.src = "https://cdn.jsdelivr.net/npm/mathpix-markdown-it@1.0.40/es5/bundle.js";` to `script.src = "https://cdn.jsdelivr.net/npm/mathpix-markdown-it@2.0.6/es5/bundle.js"`
> 
> <img alt="Screenshot 2024-11-14 at 10 06 35" width="1408" src="https://private-user-images.githubusercontent.com/32493105/386100203-0593c016-540a-4c52-8095-24cddb78b210.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzQxOTcsIm5iZiI6MTczMjA3Mzg5NywicGF0aCI6Ii8zMjQ5MzEwNS8zODYxMDAyMDMtMDU5M2MwMTYtNTQwYS00YzUyLTgwOTUtMjRjZGRiNzhiMjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAzMzgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNjk3NTkxMjU0MTFiOThlMGYxNDk0MTQ1NjlkYWYxMTIzOThhNjUyYTNlMjBkNzRjYzA5YjZlNjI0YzJhOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-xu_3d0J3nyh5o3NepqnRybvKb284XfqfxgfYEDPaSE">

 Hi I changed https://cdn.jsdelivr.net/npm/mathpix-markdown-it@2.0.6/es5/bundle.js in source but result not change

**Comment by SangVoM** [comment]
can you give me demo code ?

**Comment by OlgaRedozubova** [comment]
> Hi I changed https://cdn.jsdelivr.net/npm/mathpix-markdown-it@2.0.6/es5/bundle.js in source but result not change

It works:
<img width="1286" alt="Screenshot 2024-11-21 at 05 54 41" src="https://github.com/user-attachments/assets/394e8462-07c2-4bf1-a6e1-cc880045546f">

Example: https://github.com/Mathpix/mathpix-markdown-it/blob/master/examples/html/input-mmd-to-html.html

**Comment by SangVoM** [comment]
> > Hi I changed https://cdn.jsdelivr.net/npm/mathpix-markdown-it@2.0.6/es5/bundle.js in source but result not change
> 
> It works: <img alt="Screenshot 2024-11-21 at 05 54 41" width="1286" src="https://private-user-images.githubusercontent.com/32493105/388347651-394e8462-07c2-4bf1-a6e1-cc880045546f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjE3NjIsIm5iZiI6MTczMjE2MTQ2MiwicGF0aCI6Ii8zMjQ5MzEwNS8zODgzNDc2NTEtMzk0ZTg0NjItMDdjMi00YmYxLWE2ZTEtY2M4ODAwNDU1NDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDAzNTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNzc1M2Q2ZDU2YjgxOWUxYjY5MTUzZGU2YjY0ZTU1YmFjMGU3NWYxMzRmYTdmYThmZmMxNWFmNDRjZDViZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jM0DKRoRuEaAPmZB2I4EPjQhNyBi3U1aCbv9Au6oc-E">
> 
> Example: https://github.com/Mathpix/mathpix-markdown-it/blob/master/examples/html/input-mmd-to-html.html

But \newline not down the line ?

**Comment by SangVoM** [comment]
![Screenshot 2024-11-21 at 11 04 21](https://github.com/user-attachments/assets/743749b4-3c07-479b-86ed-4a2c9e93bcc7)
And why not render table HTML

```
<table>

 <tr>

   <th>Company</th>

   <th>Contact</th>

   <th>Country</th>

 </tr>

 <tr>

   <td>Alfreds Futterkiste</td>

   <td>Maria Anders</td>

   <td>Germany</td>

 </tr>

 <tr>

   <td>Centro comercial Moctezuma</td>

   <td>Francisco Chang</td>

   <td>Mexico</td>

 </tr>

 <tr>

   <td>Ernst Handel</td>

   <td>Roland Mendel</td>

   <td>Austria</td>

 </tr>

 <tr>

   <td>Island Trading</td>

   <td>Helen Bennett</td>

   <td>UK</td>

 </tr>

 <tr>

   <td>Laughing Bacchus Winecellars</td>

   <td>Yoshi Tannamuri</td>

   <td>Canada</td>

 </tr>

 <tr>

   <td>Magazzini Alimentari Riuniti</td>

   <td>Giovanni Rovelli</td>

   <td>Italy</td>

 </tr>

</table>
```

**Comment by OlgaRedozubova** [comment]
> But \newline not down the line ?

This is the behavior of MathJax https://mathjax.github.io/MathJax-demos-web/input-tex2svg.html

<img width="760" alt="Screenshot 2024-11-21 at 06 08 26" src="https://github.com/user-attachments/assets/c0ec77f4-71a7-4b91-9f90-bfaa5d144864">

You can try wrapping this in block math separators `$$\newline$$`

<img width="1281" alt="Screenshot 2024-11-21 at 06 10 49" src="https://github.com/user-attachments/assets/4ea44ac0-0ead-4bf1-9615-64b8570686cb">

> And why not render table HTML

Do you get it here?
https://htmlpreview.github.io/?https://github.com/Mathpix/mathpix-markdown-it/blob/master/examples/html/input-mmd-to-html.html

Everything works here:

<img width="1282" alt="Screenshot 2024-11-21 at 06 07 28" src="https://github.com/user-attachments/assets/eddfce04-7a0a-4099-b441-f8d8bb8ae294">

The option  `htmlTags: true` must be set to render HTML

```
const options = {
        htmlTags: true
};
const html = window.markdownToHTML(input, options);
```

**Comment by OlgaRedozubova** [comment]
For correct display of tabular if line breaks are needed you can use nested tables.

```
\begin{tabular}{|l|l|}
\hline
ACTIVITIES OF TEACHER AND STUDENT & MAIN CONTENT \\
\hline
\begin{tabular}{l}
Step 1. Assigning tasks \\
- Teacher: Organizes students for testing\\
- Student: Understands the teacher's requirements.\\
Step 2. Performing tasks\\
- Student: Takes the test seriously
\end{tabular}
& 
\begin{tabular}{l}
* Test content:\\
Question 1: State the basic content of\\
the current civil air defense work?.\\
Question 2: Explain the tasks of national\\
security protection?.\\
Question 3: What are the students' responsibilities\\
in the task of national security protection?. 
\end{tabular}
\\\hline
\end{tabular}
```

<img width="1513" alt="Screenshot 2024-11-21 at 06 29 58" src="https://github.com/user-attachments/assets/796a7fed-f982-44a9-9d16-913d97726c79">

**Comment by SangVoM** [comment]
Hi @OlgaRedozubova I have tried adding the` include_table_html` option but still cannot render the table html, please support me on : [codesanbox](https://codesandbox.io/p/devbox/vite-react-forked-lcfcsc) thanks very must.

**Comment by OlgaRedozubova** [comment]
> Hi @OlgaRedozubova I have tried adding the include_table_html option but still cannot render the table html, please support me on : [codesanbox](https://codesandbox.io/p/devbox/vite-react-forked-lcfcsc) thanks very must.

You need to add `htmlTags: true,`

```js
__html: MM.markdownToHTML(mathMl, {
	htmlTags: true,
        outMath: {
          include_asciimath: true,
          include_mathml: true,
          include_latex: true,
          include_svg: true,
          include_tsv: true,
          include_table_html: true,
         },
      }),
```

<img width="1515" alt="Screenshot 2024-11-21 at 10 06 15" src="https://github.com/user-attachments/assets/b05841ee-e4ad-420a-975e-3374efe28605">

**Comment by SangVoM** [comment]
HI @OlgaRedozubova, I am currently using the library function fetchLatexFromMathML in demo [codesanbox](https://codesandbox.io/p/devbox/vite-react-forked-lcfcsc) to convert from MathML to Latex. This API is a demo and may not last long. Do you have any solution to help me with this problem?

**Comment by SangVoM** [comment]
HI @OlgaRedozubova case: `$  \textcircled{C. } \ I=6\ . $ \( \quad \) $ \textcircled{D. } \ I=2\ . $ ` not render. Please support

<img width="233" alt="Screenshot 2024-11-27 at 11 12 36" src="https://github.com/user-attachments/assets/2a0d9844-d452-445c-9473-2987f1a93f2a">

**Comment by OlgaRedozubova** [comment]
> HI @OlgaRedozubova case: $  \textcircled{C. } \ I=6\ . $ \( \quad \) $ \textcircled{D. } \ I=2\ . $  not render. Please support

`\textcircled` - Not supported in MathJax. You can use `\enclose{circle}` instead.

`$\enclose{circle}{C. } \ I=6\ .$ \( \quad \) $\enclose{circle}{D. } \ I=2\ .$`

<img width="1191" alt="Screenshot 2024-11-27 at 08 50 51" src="https://github.com/user-attachments/assets/26788a59-8189-4bcf-8f3d-71c4221e612c">

Please note that if you use `$...$` separators for math - it should not contain spaces after the first `$` and before the last `$`

**Comment by SangVoM** [comment]
> > HI @OlgaRedozubova case: $  \textcircled{C. } \ I=6\ . $ ( \quad ) $ \textcircled{D. } \ I=2\ . $  not render. Please support
> 
> `\textcircled` - Not supported in MathJax. You can use `\enclose{circle}` instead.
> 
> `$\enclose{circle}{C. } \ I=6\ .$ \( \quad \) $\enclose{circle}{D. } \ I=2\ .$`
> 
> <img alt="Screenshot 2024-11-27 at 08 50 51" width="1191" src="https://private-user-images.githubusercontent.com/32493105/390295570-26788a59-8189-4bcf-8f3d-71c4221e612c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2OTI5ODksIm5iZiI6MTczMjY5MjY4OSwicGF0aCI6Ii8zMjQ5MzEwNS8zOTAyOTU1NzAtMjY3ODhhNTktODE4OS00YmNmLThmM2QtNzFjNDIyMWU2MTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA3MzEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZTJiMzc0N2ZlZmUzYzE5NmQ0YTA3ODNlYjQ0MGRhODlkZTBiMGZmNGM5MDJhMWYxMTNlNTcxYWZjYWIyZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0U5SVaIDN-muFA4E-WIa2TuS1edMIGgn8tNOCKkxhR0">
> Please note that if you use `$...$` separators for math - it should not contain spaces after the first `$` and before the last `$`
but why can `mathpix-markdown` in `vscode` be rendered ?

**Comment by OlgaRedozubova** [comment]
> but why can mathpix-markdown in vscode be rendered ?

Because vsCode uses KaTeX for all math enclosed in `$...$` or `$$...$$` separators:

<img width="1405" alt="Screenshot 2024-11-27 at 17 58 59" src="https://github.com/user-attachments/assets/ac27090f-a554-4075-a09c-0b10330d1da3">

To disable the use of KaTeX and leave only MathJax for mathematics, we need to uncheck this switch:

<img width="821" alt="Screenshot 2024-11-27 at 17 55 13" src="https://github.com/user-attachments/assets/32ad2093-d968-47c8-8a67-fe6200c6ccdc">

Result:

<img width="1280" alt="Screenshot 2024-11-27 at 18 02 38" src="https://github.com/user-attachments/assets/dc730725-62b6-4bf4-92a0-0ada2fc09715">
