### ISSUE TITLE
Can not render Unicode Greek lowercase in `$$...$$` or `$...$`.

### ISSUE THREAD

**Issue by integzz** [Mathpix/vscode-mathpix-markdown#8]
Can not render Unicode Greek lowercase in `$$...$$` or `$...$`.

**Comment by integzz** [comment]
Besides, the `\tag{}` is can not be rendered in `$$...$$`, either. Please support it.

**Comment by OlgaRedozubova** [comment]
> Can not render Unicode Greek lowercase in $$...$$ or $...$.

@integzz  What letters are you having trouble rendering? Please provide an example.

All Greek lowercase letters can be rendered using tex commands or unicode

<img width="1079" alt="Снимок экрана 2021-03-30 в 09 33 15" src="https://user-images.githubusercontent.com/32493105/112945575-271a4e00-913d-11eb-99ab-5ef496c59504.png">

<img width="1024" alt="Снимок экрана 2021-03-30 в 09 26 06" src="https://user-images.githubusercontent.com/32493105/112945612-313c4c80-913d-11eb-91e5-84fb2a3385c6.png">

**Comment by OlgaRedozubova** [comment]
> Besides, the \tag{} is can not be rendered in $$...$$, either. Please support it.

@integzz It works. Please provide an example of a formula that is not rendered correctly.
<img width="1114" alt="Снимок экрана 2021-03-30 в 09 52 28" src="https://user-images.githubusercontent.com/32493105/112945984-aad43a80-913d-11eb-8bcc-01a2dececb17.png">

**Comment by integzz** [comment]
![WeChat Screenshot_20210330163237](https://user-images.githubusercontent.com/46377665/112959474-09b5a600-9176-11eb-9076-1fbb2d5f33f5.png)

@OlgaRedozubova Thanks for your reply. It's just like this. However, I just found that it's something wrong with my VSCode. So you can close this issue. Sorry to bother you.

This is a brilliant extension.
